export const Colors ={
    red:{color:'#ff0000'},
    re100:{color:'#ffcdd2'},
    pink:{color:'#ffc0cb'},
    white:{color:'#fff'},
    green:{color:'#008000'},
    lihtGreen:{color:'#8bc34a'},
    blue:{color:'#0000ff'},
    black:{color:'#000'},
    yellow:{color:'#ffa500'},
    gray:{color:'#ccc'},
    gray2:{color:'#999'},
    prpl:{color:'#68228b'},
    deepPrpl:{color:'#673ab7'},
    blueGrey:{color:'#607d8b'},
    teal:{color:'#009688'},
    orane:{color:'#ff9800'},
    deepOrange:{color:'#ff5722'},
    lime:{color:'#cddc39'},
}

export const bgColor={
    //  (Background css )
    red: {backgroundColor: '#ff0000'}, 
    blue: {backgroundColor: '#0000ff'},
    cBlue:{backgroundColor:'#5f9ea0'},
    aliceBlue:{backgroundColor:'#f0f8ff'},
    aquam:{backgroundColor:'#7fffd4'},
    green:{backgroundColor:'#008000'},
    gray:{ backgroundColor:'#ccc'},
    yellow:{ backgroundColor:'#ffa500'},
    dark:{ backgroundColor:'#000'},
    pink:{ backgroundColor:'#ffc0cb'},
    brown:{backgroundColor:'#a52a2a'},
    voilet:{backgroundColor:'#c71585'},
    gold:{backgroundColor:'#ffb90f'},
    white:{ backgroundColor:'#fff'},
    white2:{backgroundColor:'#faebd7'},
    prpl:{ backgroundColor:'#68228b'},
    cyan:{backgroundColor:'#00ffff'},
    wood:{backgroundColor:'#deb887'}
}
